### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by Codemonkey51** [replit/blog#19]
# Issue
When you visit a blog post for example https://blog.replit.com/rui-eng all the images work fine but adding a `/` to the url  https://blog.replit.com/rui-eng/ breaks all the images and now you only see the alt text.

# Cause
This is caused by a simple fault in how images seem to be linked on the blog. They use *relative* paths so the image on https://blog.replit.com/rui-eng load just fine to https://blog.replit.com/images/...  
but images on https://blog.replit.com/rui-eng/ load to https://blog.replit.com/rui-eng/images/... which doesnt work

# Solutions
### The lazy one
Forward all traffic from `blog.replit.com/<post>/images/...` to `blog.replit.com/images/...`, this would require 0 editing of old blog posts and is the simplest solution
### Real solution
Use absolute links in the images so `/images/...` instead of `images/...` in the markdown. This would require editing older posts that use relative links

**Comment by Codemonkey51** [comment]
@piemadd btw

**Comment by piemadd** [comment]
bruh

**Comment by piemadd** [comment]
fixed (i think)
